dist: focal
language: python

git:
  depth: 1

cache:
  apt: true

python:
- '3.8'

install:
  - export PYTHON_VERSION=$(python -c "import sys;v = sys.version_info;print('%d.%d.%d' % (v[0], v[1], v[2]))")
  - export PYTHON_VERSION_SHORT=$(python -c "import sys;v = sys.version_info;print('%d.%d' % (v[0], v[1]))")
  - DIST_PACKAGES=/home/travis/virtualenv/python$PYTHON_VERSION/lib/python$PYTHON_VERSION_SHORT/site-packages
  - pip3 install coveralls codecov git+https://github.com/Nic30/pyDigitalWaveTools.git git+https://github.com/Nic30/ipCorePackager.git git+https://github.com/Nic30/pyMathBitPrecise.git git+https://github.com/Nic30/pycocotb.git
  - python3 setup.py develop
  - cd ..
  - git clone --depth=1 https://github.com/Nic30/hwtLib.git
  - pushd hwtLib
  - python3 setup.py install
  - popd
  - cd hwt
  - rm -rf $DIST_PACKAGES/hwt-*
  - ln -s hwt $DIST_PACKAGES/hwt

script:
- coverage run --branch --source=hwt ../hwtLib/setup.py test

deploy:
  provider: pypi
  user: nic30
  password:
    secure: FCgfqecSK9R3htAFosBdQyXVTmocJZVvGgvwSLI6++AVFQ60b3l9erGZmTT+L0E2vCDCVmCG0uH/QNjdna16AAhDHjt4CUx6DN11OXy9Z2suBFb2yW7XcAEI2p7m3mJnBkqRRWUURwgwn9UH7p/kJg3kCN43/wvnNuTdmE+OHuTcwrYi8J9J4yrcmGn5uGtrXbo7vWK5Y/C5hzt1XqqbLZQl4ad2UEIj5EoU41yakNN+zeDnf88rqyup4FbNeJUT46YzHd8k2TkwGvoX7p8wHJoy1kfXWtdqtenT7kfDHqVf4yO9docZbgg/2DVKheVuOxnH2HjlE4P6EJHbN/LzvZM7OKzuKFwytoYvedQivGi1bNbr7cfogXx2xf2iU+MR5IX8JQ50VTmh5BsDHofYALNKSBSrtGaQfHfihF8OKANL7AH5Qjuc1lc6hWDyioenMAo5abUcYq5bry5ZrT1NP5eCuPmLltFG2zLiYWlmr/AOjP709mI6ys519ocX4Ga2U4WDnhsyyTv8H1eSvu71e5afXgIY+Zf2rVTbImBk4NyuGMezRfcwZJWnjvYHanfQ62uFkaBQIRhM8iwf+hfpI+S4pQ/jx04pJxSLYrmQLQZnq76dNnUJUqTZotsut5EsUOG+cIqa9xT8INpde/h+cYqlpgeykvge5PmM8LDSkh0=
  on:
    tags: true
    branch: master

after_success:
- coveralls
- codecov
